### ISSUE TITLE
\xf6 and \xf7 do not work

### ISSUE THREAD

**Issue by whio** [nooodl/gs2#1]
The script is checking for \xfc and \xfd instead of the correct values.

**Comment by nooodl** [comment]
thanks! fixed in my local copy, which i'll push / get shinh to put on anagol after i test/fix some more broken stuff!

**Comment by whio** [comment]
Fixed in 7cbeb6d.

**Comment by whio** [comment]
Correction, actual fix is in 9a6e081.
