### ISSUE TITLE
join breaks on non-nested lists

### ISSUE THREAD

**Issue by whio** [nooodl/gs2#12]
example code results in an error:

04 41 41 41 05 07 42 32 "\x04AAA\x05\x07B2"

It seems like this ought to produce "ABABA", but instead complains about .extend not working because its parameter is not itself a list.

**Comment by maurisvh** [comment]
Fixed [here](https://github.com/nooodl/gs2/commit/a5e3b43521451a34951a8e401845cc7fa3b36ef1). Thank you!
