### ISSUE TITLE
"discard/trash/remove-top" opcode missing

### ISSUE THREAD

**Issue by whio** [nooodl/gs2#3]
There is no operation to discard the top value from the stack.  It is possible to work around this by substituting a pop-to-register opcode, as all four registers are rarely required, but the absence of this operation is surprising considering that its opposite (\x4c) is present.

**Comment by maurisvh** [comment]
Using the pop-to-register opcodes is by design, yeah (following the gs2 tradition of keeping track of everything you pop in the junk queue, sort of!) I've filled out register space by now, and I don't think I'll want to allocate a separate pop opcode at this point... Maybe I should alias "pop" to "pop-d"?

Leaving this open for a bit, I'm not sure what to do and I'd like to hear your thoughts!

**Comment by whio** [comment]
nip (\x46) can also be used as a substitute in many cases.  I don't think the absence of this op is a huge problem, I just ran into it on a problem where I needed to iterate n+1 times and then drop the last item from the stack.  It just seemed odd that given all the other stack manipulation operations in \x40-\x4d that this particular one was missing.

As far as opcodes go, there are a bunch of unused opcodes, mostly in \xb3 - \xc7.  Closer to the other stack manipulation ops, \x50 and \x51 appear to be unused.  I don't have a good feel for what justifies allocating an opcode - given that there exist ops for fizzbuzz and hello world.  I probably find the quick-block ops to be the most useful in terms of reducing code size.  I would say a pop opcode is not strictly needed, but it is something that I would have expected to be present.

**Comment by maurisvh** [comment]
Yeah, the ops for fizzbuzz and hello world are "jokes" (based on goruby's having 1-byte hello world -- I wanted to do better!) but I think I will actually make them special cases of other 2-operand opcodes (so when called at the beginning of the program, and the stack has only 1 value on it, they would print their special values.) I'm not sure which ones I'll put there, yet, though (but feel free to make new issues if you ever think of some feature you feel should be possible in one byte :))

I like the idea of using \x50 and \x51 -- I'd totally forgotten about leaving those unallocated! -- and I'm going to put 'pop' and 'pop2' there, I think. Thanks for bringing this to my attention.
