### ISSUE TITLE
split (\x33 \x34) has incorrect length calculation

### ISSUE THREAD

**Issue by whio** [nooodl/gs2#7]
The split() method defined uses the expression "while i <= len(a) - lb".  The use of <= instead of < hides the issue for the case where len(b) == 1, but when splitting by a longer substring/list, split(x, b) truncates the result by len(b)-1 characters.  split('abbbcdef', 'bbb') yields ['a', 'cd'] instead of ['a', 'cdef'].

**Comment by maurisvh** [comment]
Thanks! Fixed in 807643a.
