### ISSUE TITLE
regex strings (\x9c \x9d \x9e \x9f) always error

### ISSUE THREAD

**Issue by whio** [nooodl/gs2#8]
All of the regex string types pass pattern directly to re.search / re.findall / re.sub / re.split.  However, pattern is not a python string, it is a list of ordinals as it comes from the result of calling to_gs().  This causes python to return an error about being unable to hash a list.

Also, the code for regex split (\x9f) is missing the line to add the result to the stack.

**Comment by maurisvh** [comment]
Fixed this [here](https://github.com/nooodl/gs2/commit/145f051f592adf2410b54fa56b83a0a6bea279d6). Thank you!
